driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_path: test/fixtures

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.1
  - name: debian-7.9
    run_list: apt::default
  - name: debian-8.2
    run_list: apt::default
  - name: fedora-22
  - name: fedora-23
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: freebsd-9.2
    run_list:
    - recipe[freebsd::portsnap]

# # Uncomment after logging into Atlas
# - name: windows-8.1-professional
#   driver:
#     box: chef/windows-8.1-professional # private

# - name: windows-2008r2-standard
#   driver:
#     box: chef/windows-server-2008r2-standard # private

# - name: macosx-10.10
#   driver:
#     box: chef/macosx-10.10 # private

# - name: macosx-10.9
#   driver:
#     box: chef/macosx-10.9 # private

suites:
- name: default
  run_list:
  - recipe[git]
- name: source
  run_list:
  - recipe[git::source]

# servespec on windows is pretty raw.  
# os detection forces us to use a separate suite.
# rather than the usual os[:family] tricks

- name: default-windows
  includes: [
    'windows-8.1-professional', 
    'windows-2008r2-standard'
  ]
  run_list:
  - recipe[git]
