default['mzwin']['tmpdir'] = 'D:\mzzipcode'
default['mzwin']['appdir'] = 'D:\MozartV2_POC'
default['mzwin']['sitename'] = 'MozartV2_POC'
default['mzwin']['giturl'] = '"https://kdonekal:Epam1234@github.com/AllianceGlobalServices/Verisk-Mozart.git"'
node['mzwin']['backupdir'] = 'D:\Mozart_backup'
